sudo: required # Necessary when using Docker

language: cpp

compiler: gcc

services:
  - docker

install:
  - travis_wait 45 docker pull frc900/zebros-dev:latest

script:
  - docker run --name=fancy_unicorn --user ubuntu frc900/zebros-dev:latest /bin/bash -l -c
    "cd ~ &&
     sudo chown ubuntu:ubuntu 2018Offseason &&
     cd ~/2018Offseason &&
     git clone https://$GITHUB_USER:$GITHUB_PASS@github.com/FRC900/2018Offseason.git . &&
<<<<<<< HEAD
<<<<<<< HEAD
     echo \"Clone success.\" &&
     git checkout $TRAVIS_COMMIT &&
     echo \"git checkout\" &&
     git log -n1 &&
     git submodule update --init --recursive &&
     echo \"git submodule init\" &&
     ./install_ros_desktop_packages.sh &&
     echo \"install_ros_desktop_packages.sh\" &&
     cd zebROS_ws &&
     wstool update -t src --continue-on-error&&
     echo \"wstool update\" &&
     source /opt/ros/kinetic/setup.bash &&
     echo \"source setup.bash\" &&
     catkin_make &&
     echo \"catkin make\" &&
     source devel/setup.bash &&
     timeout -k 30 --preserve-status 60 roslaunch ros_control_boilerplate 2018_main_frcrobot.launch hw_or_sim:=sim output:=screen &&
     echo \"Finished Ubuntu compile.\""
  - docker run --user ubuntu frc900/zebros-dev:latest /bin/bash -l -c
    "cd ~ &&
     sudo chown ubuntu:ubuntu 2018Offseason &&
     git clone https://$GITHUB_USER:$GITHUB_PASS@github.com/FRC900/2018Offseason.git &&
     cd ./2018Offseason/ &&
     git checkout $TRAVIS_COMMIT &&
     git log -n1 &&
     git submodule update --init --recursive &&
     cd zebROS_ws &&
     wstool update -t src &&
     source /usr/arm-frc-linux-gnueabi/opt/ros/kinetic/setup.bash &&
     ./cross_build.sh &&
     echo \"Finished RoboRIO compile.\""
  - echo "Completed all tests successfully."
=======
     echo "Clone success." &&
=======
     echo \"Clone success.\" &&
>>>>>>> Using backslash quote, instead of just quote
     git checkout $TRAVIS_COMMIT &&
     echo \"git checkout\" &&
     git log -n1 &&
     git submodule update --init --recursive &&
     echo \"git submodule init\" &&
     ./install_ros_desktop_packages.sh &&
     echo \"install_ros_desktop_packages.sh\" &&
     cd zebROS_ws &&
     wstool update -t src &&
     echo \"wstool update\" &&
     source /opt/ros/kinetic/setup.bash &&
     echo \"source setup.bash\" &&
     catkin_make &&
     echo \"catkin make\" &&
     source devel/setup.bash &&
     catkin_make run_tests &&
     echo \"catkin run tests\" &&
     catkin_test_results build/test_results &&
     timeout -k 30 --preserve-status 60 roslaunch ros_control_boilerplate 2018_main_frcrobot.launch hw_or_sim:=sim output:=screen &&
     echo \"Finished Ubuntu compile.\""
#   - docker run --user ubuntu frc900/zebros-dev:latest /bin/bash -l -c
#     "cd ~ &&
#      git clone https://$GITHUB_USER:$GITHUB_PASS@github.com/FRC900/2018Offseason.git && echo "Clone success."
#      cd ./2018Offseason/ &&
#      git checkout $TRAVIS_COMMIT &&
#      git log -n1 &&
#      git submodule update --init --recursive &&
#      cd zebROS_ws &&
#      wstool update -t src &&
#      source /usr/arm-frc-linux-gnueabi/opt/ros/kinetic/setup.bash &&
#      ./cross_build.sh &&
#      echo \"Finished RoboRIO compile.\""
#   - echo "Completed all tests successfully."
>>>>>>> merged .travis.yml into gtest_dev

build:
  - true

notifications:
  email: false
  slack:
    rooms:
      frc900:RnRsEbHYnvZohI1NwZuGlsOd#github
    on_success: change
    on_failure: always
    template:
      - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch} by %{author} %{result} in %{duration}."
