sudo: required

language: cpp

compiler: gcc

services:
  - docker

before_install:
  - travis_wait docker pull eblau1/zebros-dev:latest
  - docker run eblau1/zebros-dev:latest /bin/bash -l -c "cd ~ && git clone https://$GITHUB_USER:$GITHUB_PASS@github.com/FRC900/2018RobotCode/ && cd ./2018RobotCode/ && git submodule init && git submodule update && cd zebROS_ws && wstool update -t src && source /opt/ros/kinetic/setup.bash && catkin_make && echo Yeet"
  - docker run eblau1/zebros-dev:latest /bin/bash -l -c "cd ~ && git clone https://$GITHUB_USER:$GITHUB_PASS@github.com/FRC900/2018RobotCode/ && cd ./2018RobotCode/ && git submodule init && git submodule update && cd zebROS_ws && wstool update -t src && source /usr/arm-frc-linux-gnueabi/opt/ros/kinetic/setup.bash && ./cross_build.sh && echo Yeet2"

build:
  - true

notifications:
  email: false
  slack:
    rooms:
      frc900:RnRsEbHYnvZohI1NwZuGlsOd#github
    on_success: always
    on_failure: always
    template:
      - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch} by %{author} %{result} in %{duration}. If it failed we can probably blame <@U2HRC6LR5> for the cumulative amount of time he has wasted by distracting us on slack. :black_circle:"

script:
  - echo "Yeet3"

