robot_visual:
    width: .89
    length: 1.022
    wheel_base_pos_offset: .054
    intake_length: .33655
    intake_width: .4572
    intake_angle_in: 1.4
    intake_angle_out: 2.29
    intake_position: 0.441325
    arm_length_place_forward: .38
    arm_length_place_backward: -0.32
    arm_length_place_switch: 0.48
    arm_length_intake: .1
    arm_pivot_position: .248
    

