teleop_params:
    high_scale_config_x: .1
    high_scale_config_y: 2.1
    mid_scale_config_x: .2
    mid_scale_config_y: 1.8
    low_scale_config_x: .25
    low_scale_config_y: 1.6
    switch_config_x: .3
    switch_config_y: .8
    exchange_config_x: .2
    exchange_config_y: .5
    intake_config_x: .1
    intake_config_y: .3
    default_x: .2
    default_y: .7
    timeout: 15
    exchange_delay: 0.5
