elevator_controller:
    type:       elevator_controller/ElevatorController
    lift: "lift_joint"
    intake: "intake_joint"
    pivot: "pivot_joint"
    arm_length: 0.4689729 
    max_extension: 2.375 #3.628571429 #29619 
    climb_height: 2.0 
    min_extension: 0.3575 
   
    after_shift_max_accel: 2 #fix
    after_shift_max_vel: .5 #fix

 
    hook_depth: 0.314706  #FIX
    hook_min_height: 1.41 #FIX
    hook_max_height: 1.55 #FIX
   #Fix below remove poly points 
    polygon_points: [-1.0, .325, 0.21717, .325, 0.75, .325, 0.75, -1.0, -1.0, -1.0, -1.0, .325] #~5 cm of clearance   
    lift_joint:
        joint: lift
        close_loop_values:
            - {p: 6, i: 0.0006, d: 60, f: 0, i_zone: 700}
            - {p: 6, i: 0.0006, d: 60, f: 0, i_zone: 700}
        invert_output: False
        sensor_phase: False
        feedback_type: CTRE_MagEncoder_Absolute
        conversion_factor: 0.022733
        motion_cruise_velocity: 2
        motion_acceleration: 5
    pivot_joint:
        joint: pivot
        close_loop_values:
            - {p: 6, i: 0.0006, d: 60, f: 0, i_zone: 700}
            - {p: 6, i: 0.0006, d: 60, f: 0, i_zone: 700}
        invert_output: False
        sensor_phase: False
        feedback_type: CTRE_MagEncoder_Absolute
        conversion_factor: 1 #FIX
        motion_cruise_velocity: 10
        motion_acceleration: 20
    intake_joint:
        joint: intake
        invert_output: False
        sensor_phase: False



#hypothetically might have inverts



