elevator_controller:
    type:  elevator_controller/ElevatorController
    lift: ["lift_joint", "lift_follower1_joint", "lift_follower2_joint"]
    intake: ["intake_joint", "intake_follower_joint"]
    pivot: "pivot_joint"
    arm_length: 0.4689729 
    max_extension: 2.375 #3.628571429 #29619 
    climb_height: 2.0 
    min_extension: 0.38 
   
    after_shift_max_accel: 2 #fix
    after_shift_max_vel: .5 #fix
 
    hook_depth: 0.314706  #FIX
    hook_min_height: 1.27 #FIX
    hook_max_height: 1.45 #FIX
   #Fix below remove poly points 
    polygon_points: [-1.0, .325, 0.21717, .325, 0.75, .325, 0.75, -1.0, -1.0, -1.0, -1.0, .325] #~5 cm of clearance   
    lift_joint:
        joint: lift
        close_loop_values:
            - {p: .4, i: 0.0005, d: 0.2, f: 0.1669, i_zone: 750} #{p: 7.15, i: 0.006, d: 90.0, f: 0.609381981, i_zone: 500}
            - {p: .5, i: 0.0005, d: 7.5, f: 0.0235389351901052, i_zone: 750} #{p: 7.15, i: 0.006, d: 90.0, f: 0.609381981, i_zone: 500} 
        invert_output: True
        sensor_phase: True
        feedback_type: CTRE_MagEncoder_Absolute
        conversion_factor: 0.0454676
        motion_cruise_velocity: 5 
        motion_acceleration: 10
        current_limit_continuous_amps: 60
        current_limit_enable: True
    lift_follower1_joint:
        joint: lift_follower1 
        invert_output: True
        current_limit_continuous_amps: 60
        current_limit_enable: True
    lift_follower2_joint:
        joint: lift_follower2
        invert_output: True
        current_limit_continuous_amps: 60
        current_limit_enable: True
    pivot_joint:
        joint: pivot
        close_loop_values:
            - {p: 6, i: 0.0006, d: 60, f: 0, i_zone: 700}
            - {p: 6, i: 0.0006, d: 60, f: 0, i_zone: 700}
        invert_output: False
        sensor_phase: False
        feedback_type: CTRE_MagEncoder_Absolute
        conversion_factor: 1 #FIX
        motion_cruise_velocity: 10
        motion_acceleration: 20
        current_limit_continuous_amps: 60
        current_limit_enable: True

    intake_joint:
        joint: intake
        invert_output: False
        sensor_phase: False
        current_limit_continuous_amps: 5
        current_limit_enable: True
    intake_follower_joint:
        joint: intake_follower1
        invert_output: True
        current_limit_continuous_amps: 5
        current_limit_enable: True

#hypothetically might have inverts

