#For 2018 prac bot
swerve_drive_controller:
    steering_joint_fl: 
        offset: 2.034056807
    steering_joint_fr: 
        offset: 8.762090859
    steering_joint_bl: 
        offset: -6.412034277
    steering_joint_br: 
        offset: -3.828812812
