#For 2018 comp bot
swerve_drive_controller:
    steering_joint_fl: 
        offset: 1.507903
    steering_joint_fr: 
        offset: 8.887884685
    steering_joint_bl: 
        offset: -4.703185095657
    steering_joint_br: 
        offset: -8.6869332
