#For 2018 comp bot
swerve_drive_controller:
    steering_joint_fl: 
        offset: 4.31355397553442
    steering_joint_fr: 
        offset: 9.3373410558599
    steering_joint_bl: 
        offset: 5.75549591614693
    steering_joint_br: 
        offset: 3.41310725304555
